# Generated by Django 5.2.8 on 2025-12-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician')], default='ADMIN', max_length=20),
        ),
    ]
