# Generated by Django 5.2.8 on 2025-12-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('receptionist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorconsultation',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='doctorconsultation',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorconsultation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_notes', models.TextField(blank=True)),
                ('refer_to_lab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='receptionist.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.consultation'),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='DoctorConsultation',
        ),
    ]
