# Generated by Django 5.2.8 on 2025-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_consultation_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
