# Generated by Django 5.2.8 on 2025-12-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_consultation_diagnosis_prescriptionitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTestRequest',
        ),
    ]
