# Generated by Django 5.2.8 on 2025-12-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_patient_bill'),
        ('labtech', '0002_labtestrequest_doctor_labtestrequest_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='admin_panel.patient'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
